#! /usr/bin/env python


import roslib
import rospy
import actionlib
import random
from bbot import BBotDynamixel
from bbot import BBOTTrajectoryClient



from control_msgs.msg import (
	FollowJointTrajectoryAction,
	FollowJointTrajectoryGoal,
	JointTolerance,
)

from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from moveit_msgs.msg import RobotState

import math

def initializeJoints():
	client = actionlib.SimpleActionClient('/bbot/PositionJointInterface_trajectory_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
	rospy.loginfo("Client created. Waiting for server.")
	client.wait_for_server()
	rospy.loginfo("Action client started")
	bbottraj = JointTrajectory()
	bbottraj.joint_names = ['1', '2', '3', '4', '5','6', '7']
	bbottraj.points = []
	
	zero = 2047
	opengrip = 2150
	open_grip_angle = math.pi/180.0*9.0 # degrees
	close_grip_angle = math.pi/180.0 * 65 # degrees
	closegrip = 2775
	rightturn = 4095/4
	zero = 2047
	thirtydeg = rightturn/3
	fortyfivedeg = rightturn/2
	sixtydeg = 2*rightturn/3
	jtp = JointTrajectoryPoint()
	# jtp.positions = [zero, zero, zero - rightturn, zero, zero, zero, opengrip]
	# jtp.positions = [0.0, -math.pi/4.0, -math.pi/2.0, 0.0, 0.0, 0.0, open_grip_angle]
	# jtp.positions = [0.0, 0, -math.pi/2.0, 0.0, 0.0, 0.0, open_grip_angle]
	jtp.positions = [0.0, 0, 0.0, 0.0, 0.0, 0.0, open_grip_angle]
	jtp.time_from_start = rospy.Duration.from_sec(3.0)
	# bbottraj.joint_trajectory.points.append(jtp)
	bbottraj.points.append(jtp)

	# goal = bbotGoal(traj = bbottraj) # a RobotTrajectory msg
	goal = FollowJointTrajectoryGoal()
	goal.trajectory = bbottraj 
	goal.path_tolerance = [] 
	goal.goal_tolerance = [] 
	tol = JointTolerance()
	tol.position = 0.02 # rad for revolute, m for prismatic
	for j in bbottraj.joint_names:
		goal.path_tolerance.append(tol)
		goal.goal_tolerance.append(tol)
	goal.goal_time_tolerance = rospy.Duration.from_sec(2)
	client.send_goal(goal)
	client.wait_for_result(rospy.Duration.from_sec(10))
	return client.get_result() # a boolean object


if __name__ == '__main__':
	try:
		rospy.init_node('robo_client')
		result = initializeJoints()
		print(result)
	except rospy.ROSInterruptException:
		print("program interrupted before completion")