#! /usr/bin/env python

import roslib
import rospy
import actionlib
import random
import sys
from bbot import BBOTTrajectoryClient
from bbot import bbotAnalysis
import math
import numpy as np

from control_msgs.msg import (
	FollowJointTrajectoryAction,
	FollowJointTrajectoryGoal,
	JointTolerance,
)
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from geometry_msgs.msg import Pose
from bbot import MixingTaskStateMachine
from scipy.spatial.transform import Rotation as R


##### Rotation helper functions ######
def quat_to_dcm(quat):
	# this method turns a quaternion into a direction cosine matrix using the scipy library
	r = R.from_quat(quat)
	return r.as_dcm()

def to_transformation(dcm, translation):
	# this method combines a dcm and translation vector into a 4x4 homogenous transformation matrix
	trans = np.empty((4,4))
	trans[0:3,0:3] = dcm
	trans[3,:] = [0, 0, 0, 1]
	trans[0:3,3] = translation
	return(np.matrix(trans))

def msg_to_transformation(msg):
	# this method uses the helper functions to turn a Pose msg into a 4x4 homogenous transformation matrix
	quat = [msg.orientation.x, msg.orientation.y, msg.orientation.z, msg.orientation.w]
	dcm = quat_to_dcm(quat)
	pos = [msg.position.x, msg.position.y, msg.position.z]
	return to_transformation(dcm, pos)

##### aruco callbacks #####
def cup_1_callback(msg, args):
	# this method is called everytime the pose is estimated for cup 1 aruco
	# this method updates the task_space model given the new reading
	transmatrix = msg_to_transformation(msg)
	task_space = args
	task_space.update_cup_1(transmatrix)
	
def cup_2_callback(msg, args):
	# this method is called everytime the pose is estimated for cup 2 aruco
	# this method updates the task_space model given the new reading
	transmatrix = msg_to_transformation(msg)
	task_space = args
	task_space.update_cup_2(transmatrix)

def cup_m_callback(msg, args):
	# this method is called everytime the pose is estimated for mixing cup aruco
	# this method updates the task_space model given the new reading
	transmatrix = msg_to_transformation(msg)
	task_space = args
	task_space.update_cup_m(transmatrix)

def robot_callback(msg, args):
	# this method is called everytime the pose is estimated for bbot's base aruco
	# this method updates the task_space model given the new reading
	transmatrix = msg_to_transformation(msg)
	task_space = args
	task_space.update_base(transmatrix)

##### Functions that run trajectories #####
def run_cup_1(btj, task_space, bbot):
	grip_open = -0.7
	grip_closed = 0
	pos = []
	cup1_grip_pose = task_space.TBJ
	default_config = [[-1,1,-1,1]]
	cup1_grip_q, __ = bbot.IK(cup1_grip_pose, default_config)
	cup1_grip_q = cup1_grip_q.tolist()[0]
	print(cup1_grip_q)
	cup1_grip_q.extend((grip_open, 4.0))
	# cup1_grip_pose.append()
	print(cup1_grip_q)
	print(type(cup1_grip_q))

	pos.append([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1])
	pos.append([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, grip_open, 1.0])
	# pos.append([0.0, 0.0, -1.517, 0.0, 0.0, 0.0, 1.0, 3.0])
	pos.append(cup1_grip_q)
	result = btj.sendPositionTrajectory(pos, 30)
	rospy.loginfo("Completed. error_code: " + str(result))

def run_cup_2(btj):
	pass



if __name__ == '__main__':
	try:
		rospy.init_node('demo_node')
		btj = BBOTTrajectoryClient()
		bbot = bbotAnalysis()
		task_space = MixingTaskStateMachine()

		
		# subscribe to all the pose nodes to record where the cups and robot are relative to each other
		rospy.Subscriber('aruco_1/aruco_double_j/pose', Pose, cup_1_callback, (task_space)) # sub to cup 1 pose (marker id 99)
		rospy.Subscriber('aruco_1/aruco_double_j/pose2', Pose, cup_2_callback, (task_space)) # sub to cup 2 pose (marker id 05)
		rospy.Subscriber('aruco_2/aruco_double_b/pose', Pose, cup_m_callback, (task_space)) # sub to mixing cup pose (marker id 44)
		rospy.Subscriber('aruco_2/aruco_double_b/pose2', Pose, robot_callback, (task_space)) # sub to robot base pose (marker id 26)
		rospy.sleep(1) # sleep for 1 sec while the aruco poses come in

		# grab the first cup, dump it, and return it
		run_cup_1(btj, task_space, bbot)

		# grab the second cup, dump it, and return it
		run_cup_2(btj)


	except rospy.ROSInterruptException:
		rospy.loginfo("program interrupted before completion")
