gazebo_ros_control:   
  pid_gains:
    ### PD Controller
    bbot_joint_1: {p: 5.0, i: 0.0, d: 0.4}
    bbot_joint_2: {p: 30.0, i: 0.0, d: 1.3}
    bbot_joint_3: {p: 20.0, i: 0.0, d: 0.3}
    bbot_joint_4: {p: 8.0, i: 0.0, d: 0.1}
    bbot_joint_5: {p: 2.5, i: 0.0, d: 0.0}
    bbot_joint_6: {p: 1.0, i: 0.0, d: 0.2}
    bbot_joint_7: {p: 1.0, i: 0.0, d: 0.0} 

    ### P (proportional) Controller
    # bbot_joint_1: {p: 6.64, i: 0.0, d: 0.0}
    # bbot_joint_2: {p: 6.64, i: 0.0, d: 0.0}
    # bbot_joint_3: {p: 6.64, i: 0.0, d: 0.0}
    # bbot_joint_4: {p: 6.64, i: 0.0, d: 0.0}
    # bbot_joint_5: {p: 6.64, i: 0.0, d: 0.0}
    # bbot_joint_6: {p: 6.64, i: 0.0, d: 0.0}
    # bbot_joint_7: {p: 6.64, i: 0.0, d: 0.0} 