gazebo_ros_control:   
  pid_gains:
    bbot_joint_1: {p: 5.0, i: 0.0, d: 0.4}
    bbot_joint_2: {p: 15.0, i: 0.0, d: 0.5}
    # bbot_joint_3: {p: 15.0, i: 10.0, d: 0.3}
    # bbot_joint_4: {p: 4.0, i: 0.0, d: 0.1}
    # bbot_joint_5: {p: 2.5, i: 0.0, d: 0.1}
    # bbot_joint_6: {p: 0.2, i: 0.1, d: 0.2}
    # bbot_joint_7: {p: 0.5, i: 0.0, d: 0.0} 