#iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory Controllers --------------------------------------- 

  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - bbot_joint_1
      - bbot_joint_2
      - bbot_joint_3
      - bbot_joint_4
      - bbot_joint_5
      - bbot_joint_6
      # - bbot_joint_7


    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default



  # Forward Velocity Controllers ----------------------------------
  VelocityJointInterface_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - bbot_joint_1
      - bbot_joint_2
      - bbot_joint_3
      - bbot_joint_4
      - bbot_joint_5
      - bbot_joint_6
      # - bbot_joint_7

    gains:
      bbot_joint_1: {p: 10,  d: 5, i: 1, i_clamp: 30}
      bbot_joint_2: {p: 50,  d: 5, i: 5, i_clamp: 30}
      bbot_joint_3: {p: 10,  d: 1, i: 1, i_clamp: 30}
      bbot_joint_4: {p: 10,  d: 1, i: 1, i_clamp: 30}
      bbot_joint_5: {p: 10,  d: 1, i: 1, i_clamp: 30}
      bbot_joint_6: {p: 10,  d: 1, i: 1, i_clamp: 30}
      # bbot_joint_7: {p: 10,  d: 1, i: 1, i_clamp: 30}

    constraints:
      goal_time: 0.5

    state_publish_rate: 25
    action_monitor_rate: 30
    stop_trajectory_duration: 0
